//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub use super::comments::Entity as Comments;
pub use super::images::Entity as Images;
pub use super::posts::Entity as Posts;
pub use super::users::Entity as Users;
